### PR TITLE
Passing writer and log level

### PR DESCRIPTION
**Pull request by mlesar**
Made a few changes so that we can pass writer to child loggers and also to allow for custom log level to be set on each logger.

### CODE REVIEW

**Comment by TomDeVito** [comment]
What do you mean by `custom` log level?

**Comment by mlesar** [comment]
> What do you mean by custom log level?

As it is in the `TestMultipleLogLevels()`:
```go
log := logger.New() // this logger will have level that was set over the env
regularService := NewRegularService(log)
noisyService := NewNoisyService(log.WithLog(logger.WARN)) // for this service we just want to see WARN, ERROR and CRITICAL logs
```

That is what I mean by the "custom", so that you can set a different log level for something and not use the one set by the environment variable.

**Comment by TomDeVito** [comment]
Gotcha, wasn't sure if custom meant being able to add your own log level for instance `trace` which doesn't exist as a regular log level.

I also think we should just get rid of the init and pass these values via New(..).  Init isn't really considered ideal and it's odd that a library is calling out to the OS implicitly.

**Comment by mlesar** [comment]
> 👍 before merging this, we shoulf create a release of the current version and then release this as minver upgrade. What do you think?

Yes, we can do that 👍 

> I also think we should just get rid of the init and pass these values via New(..). Init isn't really considered ideal and it's odd that a library is calling out to the OS implicitly.

This would be a breaking change(and this is a public repo), or would you rather implement this in such a way so that you could pass an array of options?

**Pull request merged**
